# TV Box Internet Radio Recorder ansible installation playbook by Dan MacDonald.

# This script is intended to be run under s9xxx Armbian as root.
# It has been tested with Armbian Jammy and currently only supports the X96 Max+.

# This playbook presumes:

# You have configured your network correctly.
# You have a USB soundcard or speaker attached to your TV box because
# onboard ALSA audio doesn't currently work for the X96 Max Plus.

---
- name: Install and configure TV Box Internet Radio Recorder
  hosts: localhost
  tasks:
    - name: Backup existing openvfd config file for X96 Max Plus 
      copy:
        src: /usr/share/openvfd/conf/x96maxplus.conf
        dest: /usr/share/openvfd/conf/x96maxplus.conf.orig
    
    - name: Edit x96maxplus.conf to only show the time 
      lineinfile:
        path: /usr/share/openvfd/conf/x96maxplus.conf
        regexp: '^function'
        line: function=''

    - name: Copy original openvfd config to create recording display config
      copy:
        src: /usr/share/openvfd/conf/x96maxplus.conf.orig
        dest: /usr/share/openvfd/conf/x96maxplus-sd.conf

    - name: Edit x96maxplus-sd.conf to enable the sd (CARD) function
      lineinfile:
        path: /usr/share/openvfd/conf/x96maxplus-sd.conf
        regexp: '^function'
        line: function='sd'

    - name: Add x96maxplus-sd.conf to armbian-led
      lineinfile:
        path: /usr/sbin/armbian-led
        insertbefore: '^\s*99'
        line: '        98 | x96maxplus-sd)  do_start x96maxplus-sd.conf ;;'
        backup: yes

    - name: Start armbian-led at boot using openvfd preset 12 ie x96maxplus.conf
      lineinfile:
        path: /etc/rc.local
        insertbefore: '^exit'
        line: armbian-led 12
        backup: yes

    - name: Compile keybinder
      shell: make chdir=keybinder
        
    - name: Copy keybinder into /usr/local/bin
      copy:
        src: keybinder/keybinder
        dest: /usr/local/bin/keybinder
        mode: a+x

    - name: Copy keybinder.conf into /etc
      copy:
        src: keybinder/keybinder.conf
        dest: /etc/keybinder.conf

    - name: Copy start-rec into /usr/local/bin
      copy:
        src: scripts/start-rec
        dest: /usr/local/bin/start-rec
        mode: a+x

    - name: Copy stop-rec into /usr/local/bin
      copy:
        src: scripts/stop-rec
        dest: /usr/local/bin/stop-rec
        mode: a+x

          # It is recommended you record to a separate micro SD card or a USB disk rather than your OS disk          
    - name: Create default stream recording target directory
      file:
        path: /root/mp3s
        state: directory

    - name: Create default playlists directory
      file:
        path: /root/playlists
        state: directory

    - name: Create moc config directory
      file:
        path: /root/.moc
        state: directory

    - name: Create JACK service override directory
      file:
        path: /etc/systemd/system/jack.service.d
        state: directory

    - name: Copy all stations playlist into /root/playlists
      copy:
        src: config/TVBIRR-All-Stations.m3u
        dest: /root/playlists/TVBIRR-All-Stations.m3u
